#!/usr/bin/env bash
# Copyright (c) 2022, Manticore Software LTD (https://manticoresearch.com)

# This program is free software; you can redistribute it and/or modify
# it under the terms of the The PHP License, version 3.01. You should have
# received a copy of the license along with this program; if you did not,
# you can find it at https://www.php.net/license/3_01.txt

# We use this script exclusively to build dev version, because static linking is hard
# For static linking we keep using the alpine docker image and buildx

# To make it work on fresh ubuntu jammy, run the following command:
# apt-get install -y libxml2 libcurl4 libonig5 libzip4

set -xe
. helper.sh

install_deps() {
  sudo apt-get update -y
  sudo apt-get install -y curl build-essential autoconf automake bison re2c libzstd-dev pkg-config git libssl-dev zlib1g-dev libzip-dev libonig-dev cmake libcurl4-openssl-dev libzip-dev librdkafka-dev
}

install_dev_deps() {
  sudo apt-get install -y libonig-dev libgmp-dev libxml2-dev
}

export -f install_deps install_dev_deps
. build-bash-base.sh "$@"


if [ "$BUILD_DEV" -eq 1 ]; then
  build_dev_conf
fi


ENABLE_SHARED=yes
ENABLE_STATIC=yes

./configure CFLAGS="-O3" --prefix="$BUILD_PREFIX" --disable-all \
  --enable-shared=$ENABLE_SHARED --enable-static=$ENABLE_STATIC --with-layout=GNU \
  --with-pear=no --disable-cgi --disable-phpdbg \
  --with-pcre-jit --enable-zstd --with-libzstd  \
  --enable-pcntl --enable-posix \
  --enable-sockets \
  --enable-ds \
  --enable-swoole \
  --with-rdkafka \
	--enable-jchash \
  --with-openssl --with-zlib --with-zip \
  --enable-filter \
  --with-curl \
  --enable-mbstring \
  "${BUILD_EXTRA[@]}"

make -j8
make install-cli