#!/usr/bin/env bash
# Copyright (c) 2022, Manticore Software LTD (https://manticoresearch.com)

# This program is free software; you can redistribute it and/or modify
# it under the terms of the The PHP License, version 3.01. You should have
# received a copy of the license along with this program; if you did not,
# you can find it at https://www.php.net/license/3_01.txt

set -e
install_deps() {
  arch=$(arch)
  # Do basic configuration of the system, and install build tools
  apk update && \
    apk add binutils cmake make libgcc musl-dev gcc g++ perl linux-headers && \
    ln -s "/usr/bin/${arch}-alpine-linux-musl-gcc-ar" "/usr/bin/${arch}-alpine-linux-musl-ar" && \
    ln -s "/usr/bin/${arch}-alpine-linux-musl-gcc-ranlib" "/usr/bin/${arch}-alpine-linux-musl-ranlib" && \
    ln -s "/usr/bin/${arch}-alpine-linux-musl-gcc-nm" "/usr/bin/${arch}-alpine-linux-musl-nm" && \
    ln -s /usr/bin/strip "/usr/bin/${arch}-alpine-linux-musl-strip" && \
    ln -s /usr/bin/objcopy "/usr/bin/${arch}-alpine-linux-musl-objcopy"
  export CROSS_COMPILE="/usr/bin/${arch}-alpine-linux-musl-"

  apk add curl git autoconf bison re2c pkgconf zlib-dev zstd-dev openssl-libs-static openssl-dev zlib-static zlib-dev
}

install_dev_deps() {
  apk add oniguruma-dev gmp-dev

  test -d libzip-1.9.2 && rm -f $_
  curl -sSL https://github.com/nih-at/libzip/releases/download/v1.9.2/libzip-1.9.2.tar.gz | tar -xzf -
  cd libzip-1.9.2 && mkdir -p build && cd build
  cmake -DBUILD_SHARED_LIBS=OFF -DENABLE_LZMA=OFF -DENABLE_BZIP2=OFF ..
  make -j4 && make install
  cd ../..
  rm -fr libzip-1.9.2

  test -d libxml2-2.10.3 && rm -f libxml2-2.10.3
  curl -sSL https://github.com/GNOME/libxml2/archive/refs/tags/v2.10.3.tar.gz | tar -xzf -
  cd libxml2-2.10.3 && mkdir -p build && cd build
  cmake -DBUILD_SHARED_LIBS=OFF -DLIBXML2_WITH_LZMA=OFF -DLIBXML2_WITH_PYTHON=OFF -DLIBXML2_WITH_ICONV=OFF -DCMAKE_BUILD_TYPE=Release ..
  make -j4 && make install
  cd ../..
  rm -fr libxml2-2.10.3
}

export -f install_deps install_dev_deps
. build-bash-base.sh "$@"

MAKE_LDFLAGS=-ldl
ENABLE_SHARED=no
ENABLE_STATIC=yes

./configure CFLAGS="-O3" --prefix="$BUILD_PREFIX" --disable-all \
  --enable-shared=$ENABLE_SHARED --enable-static=$ENABLE_STATIC --with-layout=GNU \
  --with-pear=no --disable-cgi --disable-phpdbg \
  --with-pcre-jit --enable-zstd --with-libzstd  \
  --enable-pcntl --enable-posix \
  --enable-sockets \
  --enable-zts --enable-parallel \
  --with-openssl --with-zlib \
  "${BUILD_EXTRA[@]}"

sed -ie 's/PHP_INI_ENTRY("openssl.cafile", NULL, PHP_INI_PERDIR, NULL)/PHP_INI_ENTRY("openssl.cafile", "\/etc\/ssl\/cert.pem", PHP_INI_PERDIR, NULL)/g' ext/openssl/openssl.c
sed -ie 's/-export-dynamic//g' Makefile
sed -ie 's/-o $(SAPI_CLI_PATH)/-all-static -o $(SAPI_CLI_PATH)/g' Makefile

make LDFLAGS=$MAKE_LDFLAGS -j8
make install-cli
