#!/usr/bin/env bash
# Copyright (c) 2022, Manticore Software LTD (https://manticoresearch.com)

# This program is free software; you can redistribute it and/or modify
# it under the terms of the The PHP License, version 3.01. You should have
# received a copy of the license along with this program; if you did not,
# you can find it at https://www.php.net/license/3_01.txt

set -e
install_deps() {
  sudo apt-get update -y
  sudo apt-get install -y curl build-essential autoconf automake bison re2c libzstd-dev pkg-config git libssl-dev zlib1g-dev cmake
}

install_dev_deps() {
  sudo apt-get install -y libxml2-dev libonig-dev libgmp-dev libzip-dev
}

export -f install_deps install_dev_deps
. build-bash-base.sh "$@"

CONFIGURE_LDFLAGS=
MAKE_LDFLAGS=
ENABLE_SHARED=yes
ENABLE_STATIC=no
if [[ "$BUILD_STATIC" == 1 ]]; then
  CONFIGURE_LDFLAGS=-static
  MAKE_LDFLAGS=-ldl
  ENABLE_SHARED=no
  ENABLE_STATIC=yes
fi


./configure LDFLAGS=$CONFIGURE_LDFLAGS CFLAGS="-O3" --prefix="$BUILD_PREFIX" --disable-all \
  --enable-shared=$ENABLE_SHARED --enable-static=$ENABLE_STATIC --with-layout=GNU \
  --with-pear=no --disable-cgi --disable-phpdbg \
  --with-pcre-jit --enable-zstd --with-libzstd  \
  --enable-pcntl --enable-posix \
  --enable-sockets \
  --enable-zts --enable-parallel \
  --with-openssl --with-zlib \
  --enable-opcache \
  "${BUILD_EXTRA[@]}"

if [[ "$BUILD_STATIC" == 1 ]]; then
  sed -ie 's/-export-dynamic//g' Makefile
  sed -ie 's/-o $(SAPI_CLI_PATH)/-all-static -o $(SAPI_CLI_PATH)/g' Makefile
fi

make LDFLAGS=$MAKE_LDFLAGS -j8
make install-cli
strip --strip-all dist/bin/php
