#!/usr/bin/env bash
set -e
PHP_VERSION="$1"
LZ4_REV="8ce521e086fcc4d81c57a60915676673e341ab05"

sudo xcode-select --install
sudo brew upgrade
sudo brew install gcc@11 curl autoconf automake bison re2c xxhash

curl -sSL "https://github.com/php/php-src/archive/refs/tags/php-$PHP_VERSION.tar.gz" | tar -xzf -
cd "php-src-php-$PHP_VERSION"

# Build extra extensions
cd ext

#  lz4
git clone --recursive --depth=1 https://github.com/kjdev/php-ext-lz4.git
mv php-ext-lz4 lz4
cd lz4 && git checkout "$LZ4_REV" && cd ..

cd ..

# Build main php
mkdir dist
prefix="$(pwd)/dist"
lz_lib="$(pwd)/ext/lz4/lz4/lib"
./buildconf --force
./configure YACC=/usr/local/Cellar/bison/3.8.2/bin/bison \
  LDFLAGS=-static CFLAGS="-O3" --prefix="$prefix" --disable-all \
  --enable-shared=no --enable-static=yes --with-layout=GNU \
  --with-pear=no --disable-cgi --disable-phpdbg \
  --with-pcre-jit --enable-lz4 \
  --with-lz4-includedir="$lz_lib" \
  --enable-pcntl --enable-posix
make LDFLAGS=-ldl -j8
make install-cli
strip dist/bin/php
