#!/usr/bin/env bash
# Copyright (c) 2022, Manticore Software LTD (https://manticoresearch.com)

# This program is free software; you can redistribute it and/or modify
# it under the terms of the The PHP License, version 3.01. You should have
# received a copy of the license along with this program; if you did not,
# you can find it at https://www.php.net/license/3_01.txt

set -e
PHP_VERSION="$1"
ZSTD_REV="4504e4186e79b197cfcb75d4d09aa47ef7d92fe9"
PARALLEL_REV="25ba1ee594c350b0e3e239c6b995d772d0e4fc9c"
SKIP_SYSTEM_DEPS="$2"

if [[ -z "$PHP_VERSION" ]]; then
  echo >&2 "Usage: $0 php-version [skip-system-deps]"
  exit 1
fi

if [[ -z "$SKIP_SYSTEM_DEPS" ]]; then
  sudo apt-get update -y
  sudo apt-get install -y curl build-essential autoconf automake bison re2c libzstd-dev pkg-config git libssl-dev zlib1g-dev
fi

curl -sSL "https://github.com/php/php-src/archive/refs/tags/php-$PHP_VERSION.tar.gz" | tar -xzf -
cd "php-src-php-$PHP_VERSION"

# Build extra extensions
cd ext

#  zstd
git clone --recursive --depth=1 https://github.com/kjdev/php-ext-zstd.git
mv php-ext-zstd zstd
cd zstd && git checkout "$ZSTD_REV"
# cd zstd && make && cd ..
cd ..

# parallel
git clone https://github.com/manticoresoftware/krakjoe-parallel.git parallel
cd parallel && git checkout "$PARALLEL_REV"
cd ..

cd ..

# Build main php
mkdir dist
prefix="$(pwd)/dist"
./buildconf --force
./configure LDFLAGS=-static CFLAGS="-O3" --prefix="$prefix" --disable-all \
  --enable-shared=no --enable-static=yes --with-layout=GNU \
  --with-pear=no --disable-cgi --disable-phpdbg \
  --with-pcre-jit --enable-zstd --with-libzstd  \
  --enable-pcntl --enable-posix \
  --enable-sockets \
  --enable-zts --enable-parallel \
  --with-openssl --with-zlib
sed -ie 's/-export-dynamic//g' Makefile
sed -ie 's/-o $(SAPI_CLI_PATH)/-all-static -o $(SAPI_CLI_PATH)/g' Makefile
make LDFLAGS=-ldl -j8
make install-cli
strip --strip-all dist/bin/php
