#!/usr/bin/env bash
# Copyright (c) 2022, Manticore Software LTD (https://manticoresearch.com)

# This program is free software; you can redistribute it and/or modify
# it under the terms of the The PHP License, version 3.01. You should have
# received a copy of the license along with this program; if you did not,
# you can find it at https://www.php.net/license/3_01.txt

set -e
. helper.sh

install_deps() {
  brew tap shivammathur/php
  brew install shivammathur/php/php@8.4 bash curl autoconf automake bison re2c zstd git openssl zlib cmake libzip librdkafka libiconv llvm@17
  brew link --overwrite --force shivammathur/php/php@8.4

  # Add PHP to PATH - include both versioned path and brew bin directory
  PHP_PREFIX="$(brew --prefix shivammathur/php/php@8.4)"
  BREW_PREFIX="$(brew --prefix)"
  export PATH="${PHP_PREFIX}/bin:${BREW_PREFIX}/bin:${PATH}"

  OPENSSL_PREFIX="$(brew --prefix openssl)"
  LIBRDKAFKA_PREFIX="$(brew --prefix librdkafka)"
  ICONV_PREFIX="$(brew --prefix libiconv)"
  OPENSSL_CFLAGS="-I${OPENSSL_PREFIX}/include"
  OPENSSL_LIBS="-L${OPENSSL_PREFIX}/lib -lcrypto -lssl"
  export OPENSSL_PREFIX OPENSSL_CFLAGS OPENSSL_LIBS
  export PATH="${OPENSSL_PREFIX}/bin:${PATH}"
  export LDFLAGS="-L${OPENSSL_PREFIX}/lib -L${LIBRDKAFKA_PREFIX}/lib -L${ICONV_PREFIX}/lib"
  export CPPFLAGS="-I${OPENSSL_PREFIX}/include -I${LIBRDKAFKA_PREFIX}/include -I${ICONV_PREFIX}/include"

  export PKG_CONFIG_PATH="${OPENSSL_PREFIX}/lib/pkgconfig"

  install_rust
}

install_dev_deps() {
  brew install libxml2 oniguruma libgmp
}

install_libxml2_deps() {
  brew install libxml2
}

export -f install_deps install_dev_deps install_libxml2_deps install_rust
. ./build-bash-base.sh "$@"

MAKE_LDFLAGS=
ENABLE_SHARED=yes
ENABLE_STATIC=no
if [[ "$BUILD_STATIC" == 1 ]]; then
  MAKE_LDFLAGS=-ldl
  ENABLE_SHARED=no
  ENABLE_STATIC=yes
fi

# Bison version hack
bison_ver=$(bison --version | head -n1 | cut -d' ' -f4)
if [[ "$bison_ver" =~ ^2\.[0-9]+$ ]]; then
  if which brew; then
    bison=$(brew info bison | grep files | cut -d' ' -f1)
  else
    bison=$(test -d /usr/local/opt && echo "$_" || which /usr)
  fi
  export YACC="$bison/bin/bison"
fi

# Fix the path for the librdkafka
kafka_prefix=$(brew --prefix librdkafka)
sed "s|SEARCH_PATH=\"/usr/local /usr\"|SEARCH_PATH=\"${kafka_prefix}\"|" configure > configure-new
mv configure-new configure
chmod +x configure

./configure \
  CFLAGS="-O3 -lresolv -Wno-implicit-function-declaration" \
  --prefix="$BUILD_PREFIX" --disable-all \
  --enable-shared=$ENABLE_SHARED --enable-static=$ENABLE_STATIC --with-layout=GNU \
  --with-pear=no --disable-cgi --disable-phpdbg \
  --with-pcre-jit --enable-zstd --with-libzstd  \
  --enable-pcntl --enable-posix \
  --enable-sockets \
  --enable-swoole \
  --with-rdkafka \
	--enable-jchash \
	--enable-simdjson \
	--enable-llm \
  --with-openssl --with-zlib --with-zip --with-iconv=$(brew --prefix libiconv) \
  --enable-filter \
  --with-curl \
  --enable-opcache \
  --enable-mbstring \
  --enable-shmop \
  --enable-sysvsem \
	--with-mysqli \
	--enable-mysqlnd \
  "${BUILD_EXTRA[@]}"
make LDFLAGS=$MAKE_LDFLAGS -j8
make install-cli
strip dist/bin/php

